### ISSUE TITLE
Not able to run OAS_Scenario

### ISSUE THREAD

**Issue by sumitradagar** [BerkeleyLearnVerify/Scenic#132]
![image](https://github.com/BerkeleyLearnVerify/Scenic/assets/37659902/b5235d44-623e-4ebe-b455-776d72203711)

**Comment by dfremont** [comment]
Hello Sumitra, from the traceback it looks like you're using Python 3.7 -- could you please confirm?

**Comment by sumitradagar** [comment]
Yes sir I'm using python 3.7

**Comment by dfremont** [comment]
OK, could you please also send the exact command you ran that produced the error, and the backtrace you get if you run the command adding the `-b` option?

**Comment by sumitradagar** [comment]
![image](https://github.com/BerkeleyLearnVerify/Scenic/assets/37659902/b77a4195-0b54-44e3-8879-a198080ea3d3)

**Comment by dfremont** [comment]
Hi Sumitra, can you please run the command again using the `-b` option and send the backtrace? (Please copy-paste the text into a code block in your comment rather than including a screenshot, so that other people who get the same error can search for its text. Thanks!)

**Comment by sumitradagar** [comment]
(mywork) C:\Users\Sumitra\work\Scenic>scenic examples\carla\OAS_Scenarios\oas_scenario_05.scenic -b
Beginning scenario construction...
  Loading cached version of road network...
  Loaded cached network in 0.26 seconds.
Traceback (most recent call last):
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\utils.py", line 22, in wrapper
    return self.__getattribute__(storageName)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\object_types.py", line 533, in __getattribute__
    return object.__getattribute__(proxy, name)
AttributeError: 'Car' object has no attribute '_cached_visibleRegion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sumitra\work\mywork\Scripts\scenic.exe\__main__.py", line 4, in <module>
    from scenic.__main__ import dummy
  File "C:\Users\Sumitra\work\Scenic\src\scenic\__main__.py", line 118, in <module>
    lambda: translator.scenarioFromFile(args.scenicFile,
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\errors.py", line 255, in callBeginningScenicTrace
    return func()
  File "C:\Users\Sumitra\work\Scenic\src\scenic\__main__.py", line 121, in <lambda>
    scenario=args.scenario)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\syntax\translator.py", line 125, in scenarioFromFile
    filename=fullpath, path=path, cacheImports=cacheImports)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\syntax\translator.py", line 133, in scenarioFromStream
    return constructScenarioFrom(namespace, scenario)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\syntax\translator.py", line 2384, in constructScenarioFrom
    scenario = dynScenario._toScenario(namespace)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\dynamics.py", line 573, in _toScenario
    self)   # TODO unify these!
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\scenarios.py", line 196, in __init__
    self.validate()
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\scenarios.py", line 210, in validate
    staticVisibility = self.egoObject and not needsSampling(self.egoObject.visibleRegion)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\object_types.py", line 533, in __getattribute__
    return object.__getattribute__(proxy, name)
  File "C:\Users\Sumitra\work\mywork\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\utils.py", line 24, in wrapper
    value = wrapped(self)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\object_types.py", line 592, in visibleRegion
    camera = self.position.offsetRotated(self.heading, self.cameraOffset)
  File "C:\Users\Sumitra\work\Scenic\src\scenic\core\distributions.py", line 528, in __call__
    retTy = typing.get_type_hints(func).get('return')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\typing.py", line 1001, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\typing.py", line 260, in _eval_type
    return t._evaluate(globalns, localns)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\typing.py", line 464, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Vector' is not defined

**Comment by dfremont** [comment]
Thanks, Sumitra. Could you please also post the output of `python --version`?

**Comment by sumitradagar** [comment]
(mywork) C:\Users\Sumitra\work\Scenic>python --version
Python 3.7.3

**Comment by dfremont** [comment]
OK, Python 3.7.3 is too old to work on my computer, but I'm unable to reproduce the bug on Python 3.7.9. Any chance you can upgrade to a newer Python version?

**Comment by sumitradagar** [comment]
But Sir if I upgrade the python version the Carla simulator will not work.

**Comment by dfremont** [comment]
Hi Sumitra, CARLA definitely supports Python 3.8, but if for some reason you need to stay on 3.7, you should be able to upgrade to 3.7.9 or even 3.7.16 with no problems (since they're still versions of Python 3.7).

(Note for future reference: it looks like the issue is [bpo-37838](https://github.com/python/cpython/issues/82019), which was fixed in Python 3.7.6 and 3.8.1.)

**Comment by dfremont** [comment]
Fixed in #134.
